/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:17f9de9e-6aca-4cb2-9239-f7e61c952621",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ytWKtTJ4e",
    "aws_user_pools_web_client_id": "22nltdicfgrgstpeg662sg4pnt",
    "oauth": {}
};


export default awsmobile;
